# Generated by Django 2.1.3 on 2018-11-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors_info',
            field=models.CharField(max_length=256),
        ),
    ]
