# Generated by Django 2.1.3 on 2018-11-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('path', models.CharField(max_length=256)),
                ('status_code', models.IntegerField()),
                ('headers', models.TextField()),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
